// Connection state
export type ConnectionState = 'idle' | 'connecting' | 'connected' | 'reconnecting' | 'disconnected'

// Options
export type TokenProvider = () => Promise<string>

export interface RealtimeOptions {
  /** wss://<livekit-host> */
  url: string
  /** Gets an access token. Called again when the token expires. */
  tokenProvider: TokenProvider

  /** Minimal connection options. */
  connect?: {
    autoSubscribe?: boolean // default: true
    dynacast?: boolean // default: true
  }

  /** Logical channels (topics) to use. Sending to an undeclared topic raises an error. */
  topics?: string[] // default: ['control','events','transcript']

  /** Audio publishing for server speech. */
  audioPublish?: {
    sampleRate: 48000 | 24000 | 16000 // PCM16
    channels: 1 | 2
    frameDurationMs?: 10 | 20 // default: 20
    trackName?: string // default: 'agent-audio'
  }

  /** Minimal timeout settings. */
  timeouts?: {
    connectMs?: number // default: 10000
  }

  /** Lightweight logger optimized for low overhead. */
  logger?: (level: 'debug' | 'info' | 'warn' | 'error', msg: string, meta?: unknown) => void
}

// Events
export type RealtimeEvent =
  | { type: 'state'; state: ConnectionState }
  | { type: 'data'; topic: string; payload: Uint8Array; from?: string }
  | { type: 'participant-joined'; identity: string; sid: string }
  | { type: 'participant-left'; identity: string; sid: string }
  | { type: 'warning'; code: string; message: string }
  | { type: 'error'; code: string; message: string; cause?: unknown }

// Interface
export interface RealtimeTransport {
  readonly state: ConnectionState
  on(listener: (e: RealtimeEvent) => void): () => void

  connect(opts: RealtimeOptions): Promise<void>
  disconnect(): Promise<void>

  /** Sends data. The PoC uses fixed reliable/ordered delivery; low-latency settings can be added later. */
  send(topic: string, data: Uint8Array | string): Promise<void>

  /** Publishes server speech, such as PCM16 generated by TTS. */
  startAudioPublisher(): Promise<void>
  pushPcmFrame(frame: Int16Array): Promise<void>
  stopAudioPublisher(): Promise<void>

  /** Audio controls. No-op implementations are acceptable for the PoC. */
  setMicEnabled?(enabled: boolean): Promise<void>
  setSpeakerEnabled?(enabled: boolean): Promise<void>
}
